import type { FieldMap } from "./schema";

/**
 * Content layer configuration.
 *
 * The adapter inspects your Notion data source and auto-detects which property
 * feeds each normalized field (title, slug, type, date, summary, tags, cover,
 * published, order, url, authors, pinned). Use the overrides below only when
 * auto-detection guesses wrong, or to pin a field explicitly.
 *
 * Everything not mapped here is still exposed to templates via `entry.Fields`,
 * so custom Notion columns (price, features, links, ...) work without code.
 */
export const CONTENT_FIELD_OVERRIDES: Partial<FieldMap> = {
	// slug: "Slug",
	// type: "Type",
	// date: "Date",
	// summary: "Summary",
	// tags: "Tags",
	// cover: "Image",
	// published: "Published",
	// order: "Order",
	// url: "Link",
	// authors: "Authors",
	// pinned: "Pinned",
};

/**
 * Values of the `type`/`collection` property that count as static nav pages
 * (as opposed to posts/products). Mirrors `menu-pages-collection` in
 * constants-config.json5 but is read here for clarity.
 */
export const PAGE_TYPE_VALUES = ["Page"];

/** Values treated as blog posts / articles. */
export const POST_TYPE_VALUES = ["Article", "Update"];

/** Values treated as products / case studies, served under /work/. */
export const PRODUCT_TYPE_VALUES = ["Product"];

/**
 * Notion page slugs that have a dedicated code route and must NOT also be
 * generated by the generic [...page] catch-all (would be a duplicate route).
 */
export const RESERVED_PAGE_SLUGS = [
	"work",
	"capabilities",
	"blog",
	"services",
	"stack",
	"blocks",
];